language: php
php:
- '5.6'
script: sh build.sh
env:
  global:
  - AWS_DEFAULT_REGION=ap-northeast-1
before_install:
- echo "andyhuang-test"
deploy:
  provider: s3
  access_key_id: AKIAWYQKW3OGDBE24CVF
  secret_access_key:
    secure: v0A+GBqAq8NTtpIeQD+uXFdcTvyg1j8A1mBOa6J81IVYpHPmJAT0ji98sT+VmWwZ7fy8rn8ooySE6tvM2cpMERcTjRs+8zIBqBY02gbSsXvUzwhXaIWTKYVwy7QM1V9sYfu/jy9V/JQ9wWZjTq8T+c5ivmgr6swnpKLgM1RB5a4DihtTj/RedVC/+m50IalheCAyNMg4udjc+aGz9G3OmBZoy2sKIcEZc+acsUKa9FmqK8epuEJ+Lq2lzTQuF4CGTe+t0G7z+Oyn8GhJj6wlU7qCdhhQ8qiqmrzX745VM4VSe2nzf94rCWKzqZzrgk5rAWWwmxzfUtA6lB1Mb1dbGepezsXJabQtqYAMkIiWZVO9mdapgPqjCIxby1tGwmEqOYk5haE44+9uJRPdDc7wfkcy6gAS4yfMe+tLg9CuYQgtG9KZq7Rq3lc60XeKEMyRTvVbpLVbRCBVA4jAb+zZ324+6iY8ldvnCSPYDpDeFwOUk+q6gRsibuKtHCHtqaX8Kgkrd/8kj2AGC5+sEx0AFV2VpSHQEHlbncNbTUM4R30vBdH6Je39o1uHzRWPqc1LrGvdCreFq0KFCJGs+smF5kS4MjaxRCEbT2T/49kipx2FwtN5v6n01FZLOzgToXc/2WjGseRViVtop+UNQTbdZ+bL3Ef3lQej2r7hupwcfoI=
  bucket: andyhuang-test-001
  acl: ''
