language: php
php:
- '5.6'
script: sh build.sh
env:
  global:
  - AWS_DEFAULT_REGION=ap-northeast-1
before_install:
- openssl aes-256-cbc -K $encrypted_82a9358b401d_key -iv $encrypted_82a9358b401d_iv
  -in exportAWS.sh.enc -out exportAWS.sh -d
- source exportAWS.sh
- rm -f exportAWS.sh
deploy:
  provider: s3
  access_key_id: ASIAW6L7MAQVWZCVQYJC
  secret_access_key:
    secure: OX3Ujwt1ekJ9wsFSzB7D+usbrOz1gwCmRmTeAZFxpTfQy10BmtScd0QFNqDDh18RFf94s4VqUh4dfilkRdsvePtJsuYB17vVe9K6DFyXwOvFCl1G0CHXvjWm4KPe5PKizZasDScVNkf9ek0SLK/ItN57hWG5uUdV0bt1uWZgfgLmMUqXe1hyQ5Q9HkMMxF6kjtjBTcFjfnvk1msIyNDTYm0ilUif1gGmJAnEqhCZIuiC//qtw6OPnvQn5RnMYQ+MZhStta1djh51ETQb/YQlQ9pIJl37gJe3CtJaDfvz6lMAEWwHhkHXt2qS21wcvkO4bJIaIwj0gIGsAQz1ZEh7rkN01b/d7YlLqXC0AmjaJTt+rh2qRee3oc4F1gq3QXNUsOxteAdzGMdGEvcWDNEWrzBDI0qdZyT7M1Fe7lHkPeNA30KWg3XoRVuxTYZ8q3fswjqShtYHAspnGZvqx6nGO+AD+sfwN689+kj6mc/ESDddZbT1UID/HF/LgH8ytiZc0QQdu0+Y3JYqRWUNlf7diRLc/a9X51bERRe/uOu31YDMs2d8TLphBfwfS0JgVkgkdcu9/RBwBM/iPBaVOXwSdO1CZSfTERj1tGKejGcEmRBmY3FfKxP3p5TeFgryXz2dONuv7QatPl9+Zt9wllC4+JRBvMvN5DuzgFTqub4sJiw=
  bucket: andy1huang-test-travis
  acl: ''
